[package]
name = "bgar"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.2.0"
chrono = { version = "0.4.37", features = [] }
gtk = "0.18.1"
gtk-layer-shell = "0.8.0"
sysinfo = "0.30.7"
